version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: btaru/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    env_file: .env
    image: btaru/foodgram_frontend
    volumes:
      - static:/frontend_static
  gateway:
    image: btaru/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    # command: cp -r ../docs/. /static/
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
      - ./docs/:/usr/share/nginx/html/api/docs/
