# Generated by Django 3.2.3 on 2024-07-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('shoppingcart_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipeshoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_recipes', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
