"""Константы проекта."""

TRUNCATE_AMOUNT = 20
INGREDIENT_NAME_LENGTH = 128
INGREDIENT_M_UNIT_LENGTH = 64
RECIPE_NAME_LENGTH = 256
TAG_FIELD_MAX_LENGTH = 32
USER_EMAIL_LENGTH = 254
USER_NAME_LENGTH = 150
