# Generated by Django 3.2.3 on 2024-06-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20240618_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.AlterField(
            model_name='userfavoriterecipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_recipes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
