# Generated by Django 3.2.3 on 2024-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientrecipe_unique_ingredient_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_author_recipe'),
        ),
    ]
