# Generated by Django 3.2.3 on 2024-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='user_avatars', verbose_name='Avatar image'),
        ),
    ]
